pkg-manager-command: apt
packages:
    - neovim
installer: true
teamviewer: true
ssh: true
git: true
hostname: development-station
staticIP: 192.168.4.20
subnetMask: 255.255.255.0
TeamViewerCreds:
    user: username
    pass: password
