name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Build Windows amd64 binary
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o gasible-win-amd64-${{ github.ref }}.exe

      - name: Build Linux amd64 binary
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o gasible-linux-amd64-${{ github.ref }}

      - name: Build Mac Intel binary
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o gasible-macos-amd64-${{ github.ref }}

      - name: Build Mac M1 binary
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -o gasible-macos-arm64-${{ github.ref }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            gasible-macos-arm64-${{ github.ref }}
            gasible-macos-amd64-${{ github.ref }}
            gasible-linux-amd64-${{ github.ref }}
            gasible-win-amd64-${{ github.ref }}.exe